robotic_arm_base: "joint1"
robotic_arm_tcp: "tool"
acceptable_error_m: 0.01
acceptable_error_during_trajectory_m: 0.01
acceptable_error_rad: 100 #ignore
acceptable_error_during_trajectory_rad: 100 #ignore
acceptable_error_joints: 0.05
acceptable_error_during_joint_trajectory_rad: 0.05
acceptable_error_during_trajectory_rad_in_blending_percentage: 100
acceptable_error_during_trajectory_m_in_blending_percentage: 100
acceptable_error_during_joint_trajectory_rad_in_blending_percentage: 100
number_of_joints: 3
joint_names_order: [ "art1", "art2", "art3"]
send_full_trajectories: true
trajectory_group_size: 1
send_command_topic: "/igus_arm_driver_skill/goal"
joint_states_topic: "/joint_states"

