home:
  - {Mode: MoveJJoints, Speed: 0.2, Acceleration: 0.7, Blending: 0.0, Goal: [1.57, 0.65, 2.5]}
  - {Mode: MoveJJoints, Speed: 0.2, Acceleration: 0.7, Blending: 0.0, Goal: [1.57, -0.2, 3.00]}

home_out:
  - {Mode: MoveJJoints, Speed: 0.2, Acceleration: 0.7, Blending: 0.0, Goal: [1.57, 0.65, 2.5]}

movel:
  - {Mode: MoveL, Speed:  0.05, Acceleration: 0.7, Blending: 0.0, Goal: [-0.35, -0.15 ,0.35, 0.0, 0.0, 1.0]}
  - {Mode: MoveL, Speed:  0.2, Acceleration: 0.7, Blending: 0.0, Goal: [-0.35, -0.15, 0.0, 0.0, 0.0, 1.0]}
  - {Mode: MoveL, Speed:  0.1, Acceleration: 0.7, Blending: 0.0, Goal: [-0.35, -0.35, 0.0, 0.0, 0.0, 1.0]}
  - {Mode: MoveL, Speed:  0.08, Acceleration: 0.7, Blending: 0.0, Goal: [0.35, -0.35, 0.0, 0.0, 0.0, 1.0]}
  - {Mode: MoveL, Speed:  0.2, Acceleration: 0.7, Blending: 0.0, Goal: [0.35, -0.35, 0.35, 0.0, 0.0, 1.0]}
  - {Mode: MoveL, Speed:  0.03, Acceleration: 0.7, Blending: 0.0, Goal: [0.35, -0.15, 0.35, 0.0, 0.0, 1.0]}
  - {Mode: MoveL, Speed:  0.15, Acceleration: 0.7, Blending: 0.0, Goal: [-0.35, -0.15, 0.35, 0.0, 0.0, 1.0]}

movej:
  - {Mode: MoveJ, Speed:  0.6, Acceleration: 0.7, Blending: 0.0, Goal: [0.35, -0.35, 0.0, 0.0, 0.0, 1.0]}
  - {Mode: MoveJ, Speed:  0.2, Acceleration: 0.7, Blending: 0.0, Goal: [-0.35, -0.35, 0.0, 0.0, 0.0, 1.0]}
  - {Mode: MoveJ, Speed:  0.3, Acceleration: 0.7, Blending: 0.0, Goal: [0.35, -0.15,  0.35, 0.0, 0.0, 1.0]}
  - {Mode: MoveJ, Speed:  0.5, Acceleration: 0.7, Blending: 0.0, Goal: [-0.35, -0.15,  0.35, 0.0, 0.0, 1.0]}

movelj:
  - {Mode: MoveLJoints, Speed:  0.2, Acceleration: 0.7, Blending: 0.0, Goal: [0.5, 2.0, 1.6]}
  - {Mode: MoveLJoints, Speed:  0.05, Acceleration: 0.7, Blending: 0.0, Goal: [3.1, 1.0, 1.7]}
  - {Mode: MoveLJoints, Speed:  0.15, Acceleration: 0.7, Blending: 0.0, Goal: [1.5, 1.6, 1.3]}
  - {Mode: MoveLJoints, Speed:  0.03, Acceleration: 0.7, Blending: 0.0, Goal: [2.3, 2.5, 0.9]}
  - {Mode: MoveLJoints, Speed:  0.08, Acceleration: 0.7, Blending: 0.0, Goal: [ 0.3, 0.95, 1.5]}

movejj:
  - {Mode: MoveJJoints, Speed:  0.2, Acceleration: 0.7, Blending: 0.0, Goal: [0.3, 2.5, 1.3]}
  - {Mode: MoveJJoints, Speed:  0.5, Acceleration: 0.7, Blending: 0.0, Goal: [2.5, 1.3, 2.05]}
  - {Mode: MoveJJoints, Speed:  0.6, Acceleration: 0.7, Blending: 0.0, Goal: [0.6, 2.7, 1.0]}
  - {Mode: MoveJJoints, Speed:  0.3, Acceleration: 0.7, Blending: 0.0, Goal: [2.8, 1.5, 1.1]}
  - {Mode: MoveJJoints, Speed:  0.4, Acceleration: 0.7, Blending: 0.0, Goal: [0.68, 0.97, 2.1]}

stop:
  - {Mode: MoveL, Speed: 0.1, Acceleration: 0.7, Blending: 0.05, BaseFrameId: "tool", ToolFrameId: "tool", Goal: [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]}

zeros:
  - {Mode: MoveJJoints, Speed:  0.2, Acceleration: 0.7, Blending: 0.0, Goal: [0.0, 0.0, 0.0]}
