stop:
  - {Mode: MoveL, Speed: 0.3, Acceleration: 0.7, Blending: 0.05, BaseFrameId: "tool", ToolFrameId: "tool", Goal: [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]}

rep1:
  - {Mode: MoveJ, Speed:  0.6, Acceleration: 0.7, Blending: 0.0, Goal: [-0.35, -0.35, 0.0, 0.0, 0.0, 1.0]}
  

rep2:
  - {Mode: MoveJ, Speed:  0.6, Acceleration: 0.7, Blending: 0.0, Goal: [0.35, -0.15,  0.35, 0.0, 0.0, 1.0]}

home:
  - {Mode: MoveJJoints, Speed: 0.2, Acceleration: 0.7, Blending: 0.0, Goal: [1.57, 0.65, 2.5]}
  - {Mode: MoveJJoints, Speed: 0.2, Acceleration: 0.7, Blending: 0.0, Goal: [1.57, -0.3, 3.10]}

home_out:
  - {Mode: MoveJJoints, Speed: 0.2, Acceleration: 0.7, Blending: 0.0, Goal: [1.57, 0.65, 2.5]}